version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=15172967
      - POSTGRES_DB=bd_dh2o

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dh2ovpar@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    depends_on:
      - postgres

  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
