from .clientesSerializer import ClienteSerializer
from .facturaSerializer import FacturaSerializer
from .servicioSerializer import ServicioSerializer
from .operadorSerializer import OperadorSerializer
from .mpagoSerializer import MpagoSerializer
from .detalleFacturaSerializer import DetalleFacturaSerializer
