# Generated by Django 4.2.1 on 2023-12-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria')], default='CC', max_length=3)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=11, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('ultima_limpieza', models.DateField(blank=True, null=True)),
                ('proxima_limpieza', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mpago',
            fields=[
                ('id_mpago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=11)),
                ('comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('numero_orden', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de Orden')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('facturada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.cliente')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('imagen_antes_lavado_1', models.ImageField(null=True, upload_to='reportes/')),
                ('imagen_antes_lavado_2', models.ImageField(null=True, upload_to='reportes/')),
                ('imagen_despues_lavado_1', models.ImageField(null=True, upload_to='reportes/')),
                ('imagen_despues_lavado_2', models.ImageField(null=True, upload_to='reportes/')),
                ('proxima_limpieza', models.DateField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_de_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.ordendetrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('ordenes_trabajo', models.ManyToManyField(blank=True, to='authApp.ordendetrabajo')),
            ],
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='productos',
            field=models.ManyToManyField(blank=True, to='authApp.producto'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='servicios',
            field=models.ManyToManyField(to='authApp.servicio'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authApp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('mpago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.mpago')),
                ('orden_de_trabajo', models.ForeignKey(limit_choices_to={'factura__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='authApp.ordendetrabajo')),
            ],
        ),
    ]
