# Generated by Django 4.1.1 on 2023-05-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='id_reporte',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
