# Generated by Django 4.2.1 on 2024-02-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
    ]
