# Generated by Django 4.1.1 on 2022-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
