# Generated by Django 4.2.1 on 2023-12-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(blank=True, to='authApp.producto'),
        ),
        migrations.AddField(
            model_name='factura',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='authApp.servicio'),
        ),
    ]
