# Generated by Django 4.2.1 on 2024-03-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='servicios_en_orden',
            field=models.ManyToManyField(blank=True, related_name='ordenes_de_trabajo', through='authApp.ServicioEnOrden', to='authApp.servicio'),
        ),
    ]
