# Generated by Django 4.2.1 on 2024-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='completa',
            field=models.BooleanField(default=False),
        ),
    ]
