# Generated by Django 4.2.1 on 2024-03-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_ordendetrabajo_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='mano_de_obra',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
