# Generated by Django 4.2.1 on 2024-03-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_mpago_numero_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpago',
            name='numero_cuenta',
            field=models.BigIntegerField(),
        ),
    ]
