# Generated by Django 4.1.1 on 2023-05-09 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fecha',
        ),
        migrations.AddField(
            model_name='factura',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
