# Generated by Django 4.1.1 on 2023-05-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_reporte_id_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.cliente'),
        ),
    ]
