# Generated by Django 4.2.1 on 2024-03-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpago',
            name='numero_cuenta',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
