# Generated by Django 4.2.1 on 2024-03-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_mpago_numero_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioenorden',
            name='cantidad_producto',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='servicioenorden',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.producto'),
        ),
    ]
