# Generated by Django 4.2.1 on 2024-03-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_factura_mano_de_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='mano_de_obra',
        ),
    ]
