# Generated by Django 4.1.1 on 2023-05-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_remove_factura_fecha_factura_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
