# Generated by Django 4.2.1 on 2024-03-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_mpago_numero_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_adquisicion', models.DateField()),
                ('proveedor', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.activo')),
            ],
        ),
    ]
