# Generated by Django 4.1.1 on 2023-04-29 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_repuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.cliente')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.operador')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.servicio')),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.tanque')),
            ],
        ),
    ]
