# Generated by Django 4.2.1 on 2024-01-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_cliente_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_active',
        ),
    ]
