# Generated by Django 4.2.1 on 2024-03-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_remove_factura_mano_de_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='completa',
        ),
        migrations.AddField(
            model_name='servicioenorden',
            name='reportado',
            field=models.BooleanField(default=False),
        ),
    ]
