# Generated by Django 4.1.1 on 2023-05-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_remove_factura_proxima_limpieza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='proxima_limpieza',
        ),
    ]
