# Generated by Django 4.2.1 on 2024-03-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_activo_inventarioactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_limpieza', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.cliente')),
            ],
        ),
    ]
