# Generated by Django 4.1.1 on 2023-05-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_factura_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='servicio',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='servicios',
            field=models.ManyToManyField(to='authApp.servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
