# Generated by Django 4.2.1 on 2024-03-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_servicioenorden_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioenorden',
            name='cantidad_servicio',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='servicioenorden',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.servicio'),
        ),
    ]
