# Generated by Django 4.2.1 on 2024-03-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_historiallimpieza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialLimpieza',
        ),
    ]
