# Generated by Django 4.2.1 on 2024-01-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
