# Generated by Django 4.1.1 on 2023-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_remove_reporte_proxima_limpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='proxima_limpieza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
