# Generated by Django 4.1.1 on 2023-05-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_remove_factura_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='consecutivo',
            field=models.IntegerField(default=1),
        ),
    ]
