# Generated by Django 4.1.1 on 2023-04-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
