# Generated by Django 4.2.1 on 2024-03-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_alter_servicioenorden_cantidad_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioenorden',
            name='cantidad_producto',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicioenorden',
            name='cantidad_servicio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
