# Generated by Django 4.2.1 on 2024-04-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_delete_historiallimpieza'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='operador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='operador_fotos'),
        ),
        migrations.AddField(
            model_name='operador',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
