# Generated by Django 4.1.1 on 2023-04-29 17:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_reporte_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Repuesto'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
