# Generated by Django 4.1.1 on 2023-05-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_ordendetrabajo_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='consecutivo',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
