# Generated by Django 4.2.1 on 2024-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_alter_factura_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10),
        ),
    ]
