# Generated by Django 4.1.1 on 2023-05-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_alter_ordendetrabajo_consecutivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='consecutivo',
        ),
    ]
