# Generated by Django 4.1.1 on 2023-05-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_alter_producto_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ordenes_trabajo',
            field=models.ManyToManyField(blank=True, to='authApp.ordendetrabajo'),
        ),
    ]
