# Generated by Django 4.2.1 on 2024-04-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_cuentabancaria_operador_foto_operador_numero_cuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuentaBancaria',
        ),
        migrations.AddField(
            model_name='operador',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
