# Generated by Django 4.1.1 on 2023-05-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_producto_ordenes_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
    ]
