# Generated by Django 4.1.1 on 2023-05-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_remove_ordendetrabajo_consecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='numero_orden',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
