# Generated by Django 4.2.1 on 2024-03-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_alter_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='servicio_en_orden',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authApp.servicioenorden'),
        ),
    ]
