# Generated by Django 4.1.1 on 2023-04-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_cliente_necesita_limpieza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='necesita_limpieza',
        ),
    ]
