# Generated by Django 4.2.1 on 2024-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_reporte_servicio_en_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioenorden',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
