# Generated by Django 4.1.1 on 2023-05-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_remove_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='calculated_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
