# Generated by Django 4.1.1 on 2023-05-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0010_factura_calculated_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='calculated_total',
        ),
    ]
