# Generated by Django 4.1.1 on 2023-05-12 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0010_rename_fecha_nacimiento_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente_ultima_limpieza',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
