# Generated by Django 4.1.1 on 2023-05-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_remove_factura_calculated_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
