# Generated by Django 4.1.1 on 2023-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_factura_cliente_ultima_limpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='authApp.servicio'),
        ),
    ]
