# Generated by Django 4.1.1 on 2023-05-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0012_factura_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id_servicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
