# Generated by Django 4.1.1 on 2023-04-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0012_postventa_comentario_postventa_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postventa',
            name='proxima_limpieza',
        ),
        migrations.AlterField(
            model_name='postventa',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
