# Generated by Django 4.1.1 on 2023-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0013_alter_servicio_id_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_tanque', models.CharField(max_length=100)),
                ('capacidad_tanque', models.CharField(choices=[('500', 'Tanque de 1000 litros'), ('1000', 'Tanque de 2000 litros'), ('2000', 'Tanque de 5000 litros')], max_length=4)),
                ('tuberias', models.IntegerField(default=0)),
                ('valvulas', models.IntegerField(default=0)),
                ('union_universal', models.IntegerField(default=0)),
                ('llave_paso', models.IntegerField(default=0)),
                ('valvula_check', models.IntegerField(default=0)),
                ('boya', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Repuesto',
        ),
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='tanque',
        ),
        migrations.DeleteModel(
            name='Tanque',
        ),
    ]
