# Generated by Django 4.1.1 on 2023-05-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0013_alter_factura_orden_de_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='numero_orden',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número de Orden'),
        ),
    ]
