# Generated by Django 4.1.1 on 2023-05-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0014_inventario_delete_repuesto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='marca_tanque',
            new_name='tanque',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='capacidad_tanque',
        ),
    ]
