# Generated by Django 4.1.1 on 2023-05-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0016_remove_reporte_descripcion_reporte_actividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='actividades',
            field=models.TextField(default='1. Inspeccionar el tanque elevado y sus alrededores para identificar cualquier posible riesgo o peligro en el área de trabajo, como la presencia de animales o insectos, o la acumulación de material peligroso.\n2.Verificar que la entrada y salida de agua estén cerradas y aseguradas, para evitar cualquier entrada de agua durante el proceso de lavado y desinfección.\n3.Asegurarse de tener todos los equipos de protección personal (EPP) necesarios antes de comenzar la actividad, como guantes de protección, gafas de seguridad y mascarillas.\n4. Conectar el equipo de bombeo y aspirado al tanque elevado, y retirar la mayor cantidad de agua posible del tanque.\n5. Utilizar herramientas de limpieza para remover cualquier material acumulado en el fondo del tanque, como sedimentos, lodo o residuos orgánicos.\n6. Lavar las paredes y techos del tanque con agua a alta presión, para retirar cualquier acumulación de material y desechos. Se puede utilizar un cepillo de cerdas suaves para limpiar las superficies.\n7. Utilizar el equipo de bombeo y aspirado para retirar el agua sucia y los residuos del tanque, y repetir este proceso hasta que se retire la mayor cantidad posible de material.\n8. Inspeccionar visualmente el tanque para verificar que esté completamente limpio y listo para la desinfección.'),
        ),
    ]
