# Generated by Django 4.1.1 on 2023-05-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0017_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='boyas',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='llaves_paso',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='tanques',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='tuberias',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='uniones_universales',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='valvulas',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='valvulas_check',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='inventario',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Boya',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='LlavePaso',
        ),
        migrations.DeleteModel(
            name='Tanque',
        ),
        migrations.DeleteModel(
            name='Tuberia',
        ),
        migrations.DeleteModel(
            name='UnionUniversal',
        ),
        migrations.DeleteModel(
            name='Valvula',
        ),
        migrations.DeleteModel(
            name='ValvulaCheck',
        ),
    ]
