# Generated by Django 4.1.1 on 2023-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0017_alter_reporte_actividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='actividades',
        ),
        migrations.AddField(
            model_name='reporte',
            name='actividades',
            field=models.ManyToManyField(to='authApp.actividad'),
        ),
    ]
