# Generated by Django 4.1.1 on 2023-05-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_remove_inventario_boyas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(blank=True, to='authApp.producto'),
        ),
    ]
