# Generated by Django 4.1.1 on 2023-05-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_remove_reporte_actividades_reporte_actividades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='actividades',
            new_name='actividad',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.TextField(),
        ),
    ]
