# Generated by Django 4.1.1 on 2023-05-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0019_factura_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
