# Generated by Django 4.1.1 on 2023-05-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0019_rename_actividades_reporte_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='actividad',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
