# Generated by Django 4.1.1 on 2023-05-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0024_rename_imagen_reporte_imagen_antes_lavado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='imagen_antes_lavado',
            field=models.ImageField(null=True, upload_to='reportes/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='imagen_despues_lavado',
            field=models.ImageField(null=True, upload_to='reportes/'),
        ),
    ]
