# Generated by Django 4.1.1 on 2023-05-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0026_rename_imagen_antes_lavado_reporte_imagen_antes_lavado_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='authApp.factura'),
        ),
    ]
