# Generated by Django 4.1.1 on 2023-05-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0028_alter_reporte_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='factura',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.factura'),
        ),
    ]
