# Generated by Django 4.1.1 on 2023-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0029_alter_reporte_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='total_factura',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
