# Generated by Django 4.1.1 on 2023-05-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0030_reporte_total_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='total_factura',
        ),
    ]
