# Generated by Django 4.1.1 on 2023-05-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0031_remove_reporte_factura_remove_reporte_total_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultima_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
    ]
