# Generated by Django 4.1.1 on 2023-05-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0032_cliente_ultima_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ultima_solicitud',
        ),
    ]
