# Generated by Django 4.1.1 on 2023-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0033_remove_cliente_ultima_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
