# Generated by Django 4.1.1 on 2023-06-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0036_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
