# Generated by Django 4.2.1 on 2023-06-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0040_alter_factura_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
    ]
