# Generated by Django 4.2.1 on 2023-06-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0041_remove_factura_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='facturada',
            field=models.BooleanField(default=False),
        ),
    ]
