# Generated by Django 4.2.1 on 2023-06-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0042_factura_facturada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='facturada',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='facturada',
            field=models.BooleanField(default=False),
        ),
    ]
