# Generated by Django 4.2.1 on 2023-06-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0044_alter_reporte_actividades_desarrolladas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.cliente'),
        ),
    ]
