# Generated by Django 4.2.1 on 2023-06-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0045_alter_reporte_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='cliente',
        ),
    ]
