# Generated by Django 4.2.1 on 2023-06-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0046_remove_reporte_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=None, null=True),
        ),
    ]
