# Generated by Django 4.2.1 on 2023-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0047_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(),
        ),
    ]
