# Generated by Django 4.2.1 on 2023-08-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0048_alter_factura_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_persona_juridica',
            field=models.BooleanField(default=False),
        ),
    ]
