# Generated by Django 4.2.1 on 2023-08-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0049_cliente_es_persona_juridica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='es_persona_juridica',
        ),
    ]
